spring:
  application:
    name: po-gateway-client-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/po_blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root

#mybatis-plus:
#mybatis:
#  mapper-locations: classpath*:/mapper/*.xml
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
#  mapper-locations: classpath*:/mapper/*.xml